### ISSUE TITLE
CSS transitions for input on-focus

### ISSUE THREAD

**Issue by siwalikm** [siwalikm/quick-form-css#1]
Something like this for the input boxes =>
![giphy](https://user-images.githubusercontent.com/20061595/31586667-9d1bbae6-b1f1-11e7-940d-d15f2399a64c.gif)

**Comment by siwalikm** [comment]
Something like this ? http://www.giphy.com/gifs/3ohhwuj7adykn5m3tK

**Comment by JamesSingleton** [comment]
@siwalikm,

Do you mind if I take this on? Check https://github.com/siwalikm/quick-form-css/pull/4 for the changes.

**Comment by siwalikm** [comment]
Appreciate your interest in this, can you check my comments on your pr. :)

**Comment by JamesSingleton** [comment]
Is my PR able to be merged?

**Comment by siwalikm** [comment]
Sorry for the delay @JamesSingleton, I got a little occupied with other things, will review today. 
Thanks again!

**Comment by JamesSingleton** [comment]
No worries @siwalikm, thanks for the opportunity. It was interesting trying to figure this out without class names.

**Comment by siwalikm** [comment]
@JamesSingleton Thanks for the lovely work! your commits are added in the latest release.

Btw I noticed your name is not showing up in the contributor page due to your profile being incomplete!
![image](https://user-images.githubusercontent.com/20061595/31966093-296a6e48-b927-11e7-86b9-86f9f3b3dffd.png)

Cheers 🍻

**Comment by JamesSingleton** [comment]
Hmm @siwalikm any ideas on what needs to be done? DrSarge is my old github name so that is interesting that it is still showing that. I just changed my global email in my git config to the email address I have always had on here, not sure if it is retroactive or not.

**Comment by JamesSingleton** [comment]
I would have to re-write the history of the repo to fix the email address, but GitHub doesn't recommend this. If I made another commit, I would show up. Oh well
